name: Auto Rebase 'features' on master merge

on:
  push:
    branches:
      - master

jobs:
  rebase-features:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}  # Use your PAT here
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Rebase 'features' onto 'master'
        run: |
          git checkout features
          git pull origin features
          git rebase origin/master

      - name: Push rebased 'features'
        run: |
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Mathieu-ai/tp_go_final.git features --force-with-lease
