name: Auto Rebase 'features' on master merge

on:
  push:
    branches:
      - master

jobs:
  rebase-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0 # Needed for full history (rebasing)

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all remote branches
        run: |
          git fetch --all

      - name: Checkout 'features' and rebase onto 'master'
        run: |
          git checkout features
          git reset --hard origin/features # Make sure we're exactly tracking remote
          git rebase origin/master

      - name: Push rebased 'features'
        run: |
          git fetch origin features  # Fetch latest state right before push
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Mathieu-ai/tp_go_final.git features --force-with-lease