name: Sync features branch with master

on:
  push:
    branches:
      - master

jobs:
  sync-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: |
          git fetch --all --prune

      - name: Sync features branch with master
        run: |
          # Checkout features branch
          git checkout features
          
          # Merge master into features (this will bring all new additions/deletions)
          git merge origin/master --no-edit
          
          # Push the updated features branch
          git push origin features --force-with-lease

      - name: Report sync status
        run: |
          echo "✅ Successfully synced features branch with master"
          echo "Features branch now contains all changes from master"